/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelProduccion;

import MainWindow.MainWindow;
import estruc.museo.LSMuseo;
import estruc.museo.Museo;
import estruc.museo.NodoM;
import estruc.produccion.NodoP;
import estruc.produccion.Produccion;
import estruc.sala.NodoS;
import estruc.sala.Sala;

/**
 *
 * @author Jeloska Chavez
 */
public class PanelProduccion extends javax.swing.JPanel {
    private MainWindow mainWindow;
    private LSMuseo museos;

    
    /**
     * Creates new form PanelProduccion
     */
    public PanelProduccion() {
        initComponents();
    }
     public PanelProduccion(MainWindow mainWindow) {
        initComponents();
        this.mainWindow = mainWindow;
        museos= mainWindow.getListaMuseos();
        datosATabla();
    }
    
    public void datosATabla(){
        tabla.clearTable();
        NodoM r = museos.getP();
        while(r!=null){
            Museo mx = (Museo)r.getMuseo();
            NodoS w = mx.getListaSalas().getP();
            while(w!=null){
                Sala sw = (Sala) w.getSala();
                NodoP t =  sw.getListaProducciones().getP();
                while(t!=null){
                    Produccion x = (Produccion) t.getProduccion();
                    System.out.println("Produccion");
                    produccionAFila(x, mx.getId(), sw.getIdSala());
                    t = t.getSig();
                    
                }
                w = w.getSig();
            }
            r = r.getSig();
        }

    }
  //String nombre, String fecha, String hora, String tipo, String horario, int nroEntradas, double precio
    private void produccionAFila(Produccion x, String idMuseo, String idSala){
        Object[] arr = new Object[]{x.getNombre(), x.getFecha(), x.getHora(),x.getTipo(),x.getNroEntradas(),x.getPrecio(), idMuseo, idSala};
        tabla.addRow(arr);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new componentes.CustomTable();
        jLabel16 = new javax.swing.JLabel();

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Hora", "Tipo", "Nro. Entradas", "Precio", "ID Museo", "ID Sala"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 104));
        jLabel16.setText("Producciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private componentes.CustomTable tabla;
    // End of variables declaration//GEN-END:variables
}
