/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package panelProduccion;

import MainWindow.MainWindow;
import estruc.museo.LSMuseo;
import estruc.museo.NodoM;
import estruc.produccion.NodoP;
import estruc.produccion.Produccion;
import estruc.sala.NodoS;

/**
 *
 * @author Jeloska Chavez
 */
public class PanelProduccionesMasCostosas extends javax.swing.JPanel {

    /** Creates new form PanelProduccionesMasCostosas */
    private MainWindow mainWindow;
    private LSMuseo listaMuseo;
    public PanelProduccionesMasCostosas(MainWindow mainWindow) {
        initComponents();
        this.mainWindow = mainWindow;
        listaMuseo = mainWindow.getListaMuseos();
        datosATabla();
    }
    public double buscarMasCostosas(){
        double may = 0;
        NodoM r = listaMuseo.getP();
        while(r!=null){
            NodoS w = r.getMuseo().getListaSalas().getP();
            while(w!=null){
                NodoP s = w.getSala().getListaProducciones().getP();
                if(s!=null){
                    if(s.getProduccion().getPrecio()>may)
                        may = s.getProduccion().getPrecio();
                    s = s.getSig();
                }
                w = w.getSig();
            }
            r = r.getSig();
        }
        return may;
        
    }
    public void datosATabla(){
        tabla.clearTable();
        double may = buscarMasCostosas();
        NodoM r = listaMuseo.getP();
        while(r!=null){
            NodoS w = r.getMuseo().getListaSalas().getP();
            while(w!=null){
                NodoP s = w.getSala().getListaProducciones().getP();
                if(s!=null){
                    if(s.getProduccion().getPrecio()==may)
                        ProduccionAFila(s.getProduccion());
                    s = s.getSig();
                }
                w = w.getSig();
            }
            r = r.getSig();
        }
    }
    private void ProduccionAFila(Produccion x) {
        Object[] arr = new Object[]{x.getNombre(), x.getFecha(), x.getHora(), x.getTipo(), x.getNroEntradas(), x.getPrecio()};
        tabla.addRow(arr);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new componentes.CustomTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("+");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Hora", "Tipo", "Nro. Entradas", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 104));
        jLabel18.setText("Costosas");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 104));
        jLabel19.setText("Producciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private componentes.CustomTable tabla;
    // End of variables declaration//GEN-END:variables

}
