/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelSalas;

import MainWindow.MainWindow;
import estruc.museo.LSMuseo;
import estruc.museo.Museo;
import estruc.museo.NodoM;
import estruc.sala.LSSala;
import estruc.sala.NodoS;
import estruc.sala.Sala;

/**
 *
 * @author jeloskaisabel
 */
public class PanelSalas extends javax.swing.JPanel {
    
    /*private String nombre, idSala;
    private int capacidad;
    private LDNormal listaProducciones;*/

    /**
     * Creates new form PanelSalas
     */
    private MainWindow mainWindow;
    private LSMuseo museos;
    public PanelSalas() {
        initComponents();
    }
    public PanelSalas(MainWindow mainWindow){
        initComponents();
        this.mainWindow = mainWindow;
        museos = mainWindow.getListaMuseos();
        datosATabla();
    }
    
    public void datosATabla(){
        tabla.clearTable();        
        NodoM q = museos.getP();
        while(q != null){
            Museo museo = (Museo)q.getMuseo();
            NodoS r = museo.getListaSalas().getP();
            while(r!=null){
                Sala sx = (Sala)r.getSala();
                SalaAFila(sx, museo.getId(), sx.getListaProducciones().nroNodos());
                r = r.getSig();
            }
            q = q.getSig();
            
        }
    }
    /*private String nombre, idSala;
    private int capacidad;
    private LDNormal listaProducciones;*/
    private void SalaAFila(Sala x, String idMuseo, int n){
        Object[] arr = new Object[]{x.getNombre(), x.getIdSala(), x.getCapacidad(), n, idMuseo};
        tabla.addRow(arr);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new componentes.CustomTable();

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "ID Sala", "Capacidad", "Nro. Prodcucciones", "ID Museo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private componentes.CustomTable tabla;
    // End of variables declaration//GEN-END:variables
}
