/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelVisitante;

import MainWindow.MainWindow;
import estructuras.Listas.LDNormal;
import estructuras.Listas.LSNormal;
import estructuras.Listas.NodoD;
import estructuras.Listas.NodoS;
import estructuras.Pila.Pila;
import museo.Museo;
import museo.Sala;
import personas.Artista;
import personas.Visitante;
import produccion.Produccion;

/**
 *
 * @author Jeloska Chavez
 */
public class PanelVisitante extends javax.swing.JPanel {

    /**
     * Creates new form PanelVisitante
     */
    private MainWindow mainWindow;
    private LDNormal museos;

    public PanelVisitante() {
        initComponents();
    }

    public PanelVisitante(MainWindow mainWindow) {
        initComponents();
        this.mainWindow = mainWindow;
        museos = mainWindow.getListaMuseos();
        datosATabla();
    }

    public void datosATabla() {
        tabla.clearTable();
        NodoD r = museos.getP();
        while (r != null) {
            Museo mx = (Museo) r.getDato();
            String idMx = "(" + mx.getId() + ") " + mx.getNombre();

            LSNormal lsx = mx.getListaSalas();
            NodoS w = lsx.getCabecera();
            while (w != null) {
                Sala sx = (Sala) w.getDato();

                LDNormal lpx = sx.getListaProducciones();
                NodoD z = lpx.getP();
                while (z != null) {
                    Produccion px = (Produccion) z.getDato();
                    Pila pvx = px.getPilaVisitantes();
                    Pila aux = new Pila(pvx.nElem());
                    while (!pvx.esVacia()) {
                        Visitante vx = (Visitante) pvx.eliminar();
                        visitanteAFila(vx, idMx, sx.getIdSala(), px.getNombre());
                        aux.adicionar(vx);
                       
                    }
                    pvx.vaciar(aux);
                    z = z.getSig();

                }

                w = w.getSig();
            }

            r = r.getSig();
        }
    }

    //ci, edad, nombre, paterno, materno, genero    
    private void visitanteAFila(Visitante x, String idMuseo, String idSala, String nomProd) {
        Object[] arr = new Object[]{x.getNombre(), x.getApellido(), x.getCi(), x.getGenero(), x.getIdTicket(), idMuseo, idSala, nomProd};
        tabla.addRow(arr);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new componentes.CustomTable();

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "CI", "Genero", "ID Ticket", "IDMuseo", "IDSala", "Produccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private componentes.CustomTable tabla;
    // End of variables declaration//GEN-END:variables
}
