/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelVisitante;

import MainWindow.MainWindow;
import estruc.museo.LSMuseo;
import estruc.museo.NodoM;
import estruc.persona.NodoV;
import estruc.persona.Visitante;
import estruc.produccion.NodoP;
import estruc.produccion.Produccion;
import estruc.sala.NodoS;

/**
 *
 * @author Jeloska Chavez
 */
public class PanelVisitanteBuscar extends javax.swing.JPanel {

    /**
     * Creates new form PanelVisitanteBuscar
     */
    private MainWindow mainWindow;
    private LSMuseo listaMuseo;

    public PanelVisitanteBuscar(MainWindow mainWindow) {
        initComponents();
        this.mainWindow = mainWindow;
        listaMuseo = mainWindow.getListaMuseos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valorNeto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fieldCI = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new componentes.CustomTable();
        fieldNombre = new javax.swing.JTextField();
        fieldApellido = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        buscarCI = new javax.swing.JButton();
        buscarNombre = new javax.swing.JButton();
        buscarApellido = new javax.swing.JButton();

        valorNeto.setBackground(new java.awt.Color(218, 228, 232));
        valorNeto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 104)));
        valorNeto.setCaretColor(new java.awt.Color(0, 0, 104));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 104));
        jLabel18.setText("CI");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 104));
        jLabel20.setText("Nombre");

        fieldCI.setBackground(new java.awt.Color(218, 228, 232));
        fieldCI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 104)));
        fieldCI.setCaretColor(new java.awt.Color(0, 0, 104));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 104));
        jLabel19.setText("Visitantes");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "CI", "Género", "ID Ticket", "ID Museo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        fieldNombre.setBackground(new java.awt.Color(218, 228, 232));
        fieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 104)));
        fieldNombre.setCaretColor(new java.awt.Color(0, 0, 104));

        fieldApellido.setBackground(new java.awt.Color(218, 228, 232));
        fieldApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 104)));
        fieldApellido.setCaretColor(new java.awt.Color(0, 0, 104));
        fieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldApellidoActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 104));
        jLabel21.setText("Apellido");

        buscarCI.setBackground(new java.awt.Color(0, 0, 104));
        buscarCI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarCI.setForeground(new java.awt.Color(255, 255, 255));
        buscarCI.setText("🔎");
        buscarCI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscarCI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarCIMouseClicked(evt);
            }
        });
        buscarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCIActionPerformed(evt);
            }
        });

        buscarNombre.setBackground(new java.awt.Color(0, 0, 104));
        buscarNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarNombre.setForeground(new java.awt.Color(255, 255, 255));
        buscarNombre.setText("🔎");
        buscarNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarNombreMouseClicked(evt);
            }
        });
        buscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNombreActionPerformed(evt);
            }
        });

        buscarApellido.setBackground(new java.awt.Color(0, 0, 104));
        buscarApellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarApellido.setForeground(new java.awt.Color(255, 255, 255));
        buscarApellido.setText("🔎");
        buscarApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscarApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarApellidoMouseClicked(evt);
            }
        });
        buscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldCI, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldNombre))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldApellido))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(valorNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(buscarCI)
                            .addComponent(jLabel21)
                            .addComponent(buscarNombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(valorNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApellidoActionPerformed

    private void buscarCIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarCIMouseClicked
        // TODO add your handling code here:
        datosATabla(Integer.parseInt(fieldCI.getText()), "Ci", null, null);

    }//GEN-LAST:event_buscarCIMouseClicked

    private void buscarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCIActionPerformed
        // TODO add your handling code here:

        /*p1_addMuseumPanel.setVisible(false);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        reset();*/
    }//GEN-LAST:event_buscarCIActionPerformed

    private void buscarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarNombreMouseClicked
        // TODO add your handling code here:
        datosATabla(-1, "Nombre", fieldNombre.getText(), null);
    }//GEN-LAST:event_buscarNombreMouseClicked

    private void buscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarNombreActionPerformed

    private void buscarApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarApellidoMouseClicked
        // TODO add your handling code here:
        datosATabla(-1, "Apellido", null, fieldApellido.getText());
    }//GEN-LAST:event_buscarApellidoMouseClicked

    private void buscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarApellidoActionPerformed
    public void datosATabla(int ci, String criterio, String nombre, String apellido) {
        tabla.clearTable();
        NodoM r = listaMuseo.getP();
        while (r != null) {
            NodoS s = r.getMuseo().getListaSalas().getP();
            while (s != null) {
                NodoP w = s.getSala().getListaProducciones().getP();
                while (w != null) {
                    NodoV t = w.getProduccion().getListaVisitantes().getP();
                    while (t != null) {
                        boolean sw = false;
                        if (criterio.equals("Ci")) {
                            if (t.getDato().getCi() == ci) {
                                sw = true;
                            }
                        } else if (criterio.equals("Nombre")) {
                            if (t.getDato().getNombre().equals(nombre)) {
                                sw = true;
                            }
                        } else if (criterio.equals("Apellido")) {
                            if (t.getDato().getNombre().equals(apellido)) {
                                sw = true;
                            }
                        }
                        if (sw) {
                            VisitanteAFila(t.getDato(), r.getMuseo().getId());
                        }
                        t = t.getSig();
                    }
                    w = w.getSig();
                }
                s = s.getSig();

            }
            r = r.getSig();
        }
    }

    private void VisitanteAFila(Visitante x, String idMuseo) {
        Object[] arr = new Object[]{x.getNombre(), x.getApellido(), x.getCi(), x.getGenero(), x.getIdTicket(), idMuseo};
        tabla.addRow(arr);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarApellido;
    private javax.swing.JButton buscarCI;
    private javax.swing.JButton buscarNombre;
    private javax.swing.JTextField fieldApellido;
    private javax.swing.JTextField fieldCI;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jScrollPane1;
    private componentes.CustomTable tabla;
    private javax.swing.JTextField valorNeto;
    // End of variables declaration//GEN-END:variables
}
