/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelArtista;

import MainWindow.MainWindow;
import estruc.museo.LSMuseo;
import estruc.sala.NodoS;
import estruc.museo.Museo;
import estruc.museo.NodoM;
import estruc.persona.Artista;
import estruc.persona.NodoA;
import estruc.produccion.LSProduccion;
import estruc.produccion.NodoP;
import estruc.sala.LSSala;
import estruc.sala.Sala;
import estruc.produccion.Produccion;


public class PanelArtista extends javax.swing.JPanel {

    /**
     * Creates new form PanelArtista
     */
    private MainWindow mainWindow;
    private LSMuseo museos;

    public PanelArtista() {
        initComponents();
    }

    public PanelArtista(MainWindow mainWindow) {
        initComponents();
        this.mainWindow = mainWindow;
        museos = mainWindow.getListaMuseos();
        datosATabla();
    }

    public void datosATabla() {
        tabla.clearTable();
        NodoM r = museos.getP();
        while (r != null) {
            Museo mx = (Museo) r.getMuseo();
            String idMx = "(" + mx.getId() + ") " + mx.getNombre();
            LSSala lsx = mx.getListaSalas();
            NodoS w = lsx.getP();
            while (w != null) {
                Sala sx = w.getSala();
                LSProduccion lpx = sx.getListaProducciones();
                NodoP z = lpx.getP();
                while (z != null) {
                    Produccion px = z.getProduccion();
                    NodoA u = px.getListaArtistas().getP();
                    while (u != null) {
                        Artista ax = u.getDato();
                        artistaAFila(ax, idMx, ""+sx.getIdSala(), px.getNombre());
                        u = u.getSig();
                    }
                    z = z.getSig();

                }

                w = w.getSig();
            }

            r = r.getSig();
        }
    }

    //ci, edad, nombre, paterno, materno, genero    
    private void artistaAFila(Artista x, String idMuseo, String idSala, String nomProd) {
        Object[] arr = new Object[]{x.getNombre(), x.getApellido(), x.getCi(), x.getGenero(), x.getTipo(), idMuseo, idSala, nomProd};
        tabla.addRow(arr);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new componentes.CustomTable();
        jLabel16 = new javax.swing.JLabel();

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "CI", "Genero", "Categoria", "IDMuseo", "IDSala", "Produccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 104));
        jLabel16.setText("Artistas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private componentes.CustomTable tabla;
    // End of variables declaration//GEN-END:variables
}
