/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegistroSalas;

import MainWindow.MainWindow;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import estruc.museo.Museo;
import estruc.sala.LSSala;
import estruc.sala.Sala;

/**
 *
 * @author Jeloska Chavez
 */
public class RegistroSalas extends javax.swing.JFrame {

    /**
     * Creates new form RegistroSalas
     */
    private String idMuseo;
    private LSSala listaSalas;
    private MainWindow mainWindow;

    public RegistroSalas(String id, LSSala listaSalas, MainWindow mainWindow) {
        idMuseo = id;
        this.listaSalas = listaSalas;
        this.mainWindow = mainWindow;
        initComponents();
    }

    void reset() {
        nombreSala.setText("");
        capacidadSala.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        capacidadSala = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        idSala = new javax.swing.JRadioButton();
        nombreSala = new javax.swing.JTextField();
        agregarSala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(218, 228, 232));

        mainPanel.setBackground(new java.awt.Color(218, 228, 232));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 104));
        jLabel1.setText("Registrar Sala");

        jPanel1.setBackground(new java.awt.Color(218, 228, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sala", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 104))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 104));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 41, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 104));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 67, 292, 16));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 104));
        jLabel2.setText("Capacidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 93, -1, -1));

        capacidadSala.setBackground(new java.awt.Color(218, 228, 232));
        capacidadSala.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        capacidadSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        capacidadSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacidadSalaActionPerformed(evt);
            }
        });
        jPanel1.add(capacidadSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 87, 96, 32));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 104));
        jLabel38.setText("ID:");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 93, -1, -1));

        idSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idSala.setForeground(new java.awt.Color(0, 0, 104));
        idSala.setText("ID");
        idSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idSalaMouseClicked(evt);
            }
        });
        jPanel1.add(idSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 91, -1, -1));

        nombreSala.setBackground(new java.awt.Color(218, 228, 232));
        nombreSala.setBorder(null);
        nombreSala.setCaretColor(new java.awt.Color(0, 0, 104));
        nombreSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSalaActionPerformed(evt);
            }
        });
        jPanel1.add(nombreSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 292, 30));

        agregarSala.setBackground(new java.awt.Color(255, 51, 0));
        agregarSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarSala.setForeground(new java.awt.Color(255, 255, 255));
        agregarSala.setText("Agregar Sala");
        agregarSala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(agregarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void capacidadSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacidadSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadSalaActionPerformed

    private void idSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idSalaMouseClicked
        String idText = idMuseo + "-" + String.format("%d", listaSalas.nroNodos() + 1);
        idSala.setText(idText);
    }//GEN-LAST:event_idSalaMouseClicked

    private void nombreSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSalaActionPerformed

    private void agregarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSalaActionPerformed

        // Obtener datos de los campos de texto
        String nombre, id;
        int capacidad = capacidadSala.getSelectedIndex();
        nombre = nombreSala.getText();
        id = idSala.getText();
        // Validacion de campos no vacios
        if (nombre.equals("") || nombreSala.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos",
                    "Error al registrar el museo", JOptionPane.ERROR_MESSAGE);

        } else {
            Sala sx = new Sala();
            sx.setCapacidad(capacidad);
            sx.setIdSala(id);
            sx.setNombre(nombre);
            listaSalas.adiFinal(sx);
            mainWindow.getPanel2().datosATabla();
            JOptionPane.showMessageDialog(null, "Sala agregada exitosamente");
            reset();
            this.dispose();
        }
        


    }//GEN-LAST:event_agregarSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    //Aqui main!!!!

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarSala;
    private javax.swing.JComboBox<String> capacidadSala;
    private javax.swing.JRadioButton idSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nombreSala;
    // End of variables declaration//GEN-END:variables
}
